name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/nix-installer-action@v20

      - run: nix -vL --show-trace flake check

      - run: nix -vL --show-trace build .#void40 --out-link result-void40

      - run: nix -vL --show-trace build .#photon --out-link result-photon

      - uses: actions/upload-artifact@v5
        with:
          name: zmk_firmware
          path: |
            result-void40
            result-photon
